version: "2"
linters:
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - durationcheck
    - exhaustive
    - forbidigo
    - gochecknoinits
    - gocritic
    - gomodguard
    - gosec
    - importas
    - misspell
    - mnd
    - nilerr
    - nolintlint
    - predeclared
    - revive
    - unconvert
    - unparam
    - wastedassign
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    forbidigo:
      forbid:
        - pattern: CoreV1\(\)\.Endpoints(# use DiscoveryV1 EndpointSlices API instead)?
        - pattern: corev1\.Endpoint(# use DiscoveryV1 EndpointSlices API instead)?
      exclude-godoc-examples: false
    gomodguard:
      blocked:
        modules:
          - github.com/ghodss/yaml:
              recommendations:
                - sigs.k8s.io/yaml
          - gopkg.in/yaml.v2:
              recommendations:
                - sigs.k8s.io/yaml
          - gopkg.in/yaml.v3:
              recommendations:
                - sigs.k8s.io/yaml
          - github.com/pkg/errors:
              recommendations:
                - fmt
                - errors
          - golang.org/x/net/context:
              recommendations:
                - context
    importas:
      alias:
        - pkg: k8s.io/api/core/v1
          alias: corev1
        - pkg: k8s.io/api/apps/v1
          alias: appsv1
        - pkg: k8s.io/api/networking/v1
          alias: netv1
        - pkg: k8s.io/api/networking/v1beta1
          alias: netv1beta1
        - pkg: k8s.io/api/discovery/v1
          alias: discoveryv1
        - pkg: k8s.io/api/extensions/v1beta1
          alias: extv1beta1
        - pkg: k8s.io/api/rbac/v1
          alias: rbacv1
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
        - pkg: sigs.k8s.io/gateway-api/apis/(v[\w\d]+)
          alias: gateway${1}
      no-unaliased: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/kong/kubernetes-testing-framework)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
