run:
  timeout: 5m
linters:
  enable:
  - asciicheck
  - bodyclose
  - depguard
  - dogsled
  - durationcheck
  - errcheck
  - exhaustive
  - exportloopref
  - gochecknoinits
  - gofmt
  - goimports
  - gomnd
  - gomodguard
  - gosec
  - gci
  - gosimple
  - govet
  - importas
  - ineffassign
  - megacheck
  - misspell
  - nilerr
  - nolintlint
  - predeclared
  - revive
  - staticcheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - wastedassign

linters-settings:
  gci:
    sections:
    - standard
    - default
    - prefix(github.com/kong/kubernetes-testing-framework)
  gomodguard:
    blocked:
      modules:
      - github.com/ghodss/yaml:
          recommendations:
          - sigs.k8s.io/yaml
      - gopkg.in/yaml.v2:
          recommendations:
          - sigs.k8s.io/yaml
      - gopkg.in/yaml.v3:
          recommendations:
          - sigs.k8s.io/yaml

issues:
  fix: true
