run:
  timeout: 5m
linters:
  enable:
  - asciicheck
  - bodyclose
  - deadcode
  - depguard
  - dogsled
  - durationcheck
  - errcheck
  - exhaustive
  - exportloopref
  - gochecknoinits
  - gofmt
  - goimports
  - gomnd
  - gosec
  - gosimple
  - govet
  - importas
  - ineffassign
  - megacheck
  - misspell
  - nilerr
  - nolintlint
  - predeclared
  - revive
  - staticcheck
  - structcheck
  - typecheck
  - unconvert
  - unparam
  - varcheck
  - wastedassign
