run:
  timeout: 5m
linters:
  enable:
  - asciicheck
  - bodyclose
  - depguard
  - dogsled
  - durationcheck
  - errcheck
  - exhaustive
  - exportloopref
  - gochecknoinits
  - gofmt
  - goimports
  - gomnd
  - gosec
  - gci
  - gosimple
  - govet
  - importas
  - ineffassign
  - megacheck
  - misspell
  - nilerr
  - nolintlint
  - predeclared
  - revive
  - staticcheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - wastedassign

linters-settings:
  gci:
    sections:
    - standard
    - default
    - prefix(github.com/kong/kubernetes-testing-framework)

issues:
  fix: true
