run:
  timeout: 5m
linters:
  enable:
  - asciicheck
  - bodyclose
  - dogsled
  - durationcheck
  - errcheck
  - exhaustive
  - exportloopref
  - forbidigo
  - gochecknoinits
  - gofmt
  - goimports
  - gomnd
  - gomodguard
  - gosec
  - gci
  - gosimple
  - govet
  - importas
  - ineffassign
  - megacheck
  - misspell
  - nilerr
  - nolintlint
  - predeclared
  - revive
  - staticcheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - wastedassign

linters-settings:
  gci:
    sections:
    - standard
    - default
    - prefix(github.com/kong/kubernetes-testing-framework)
  gomodguard:
    blocked:
      modules:
      - github.com/ghodss/yaml:
          recommendations:
          - sigs.k8s.io/yaml
      - gopkg.in/yaml.v2:
          recommendations:
          - sigs.k8s.io/yaml
      - gopkg.in/yaml.v3:
          recommendations:
          - sigs.k8s.io/yaml
  importas:
    no-unaliased: true
    alias:
      - pkg: k8s.io/api/core/v1
        alias: corev1
      - pkg: k8s.io/api/apps/v1
        alias: appsv1
      - pkg: k8s.io/api/networking/v1
        alias: netv1
      - pkg: k8s.io/api/networking/v1beta1
        alias: netv1beta1
      - pkg: k8s.io/api/discovery/v1
        alias: discoveryv1
      - pkg: k8s.io/api/extensions/v1beta1
        alias: extv1beta1
      - pkg: k8s.io/api/rbac/v1
        alias: rbacv1

      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: metav1
      - pkg: sigs.k8s.io/gateway-api/apis/(v[\w\d]+)
        alias: gateway${1}
  forbidigo:
    exclude_godoc_examples: false
    forbid:
      - 'CoreV1\(\)\.Endpoints(# use DiscoveryV1 EndpointSlices API instead)?'
      - 'corev1\.Endpoint(# use DiscoveryV1 EndpointSlices API instead)?'
issues:
  fix: true
