name: lint

concurrency:
  # Run only for most recent commit in PRs but for all tags and commits on main
  # Ref: https://docs.github.com/en/actions/using-jobs/using-concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
    - '*'
  push:
    branches:
    - 'main'
    tags:
    - '*'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  golangci-lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0

    - name: setup golang
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: go.mod

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
      with:
        skip-cache: true # actions/setup-go from v4 handles caching for us
