name: release-testing

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'a release tag that will be created upon success'
        required: true

jobs:

  # --------------------------------------------------------------------------
  # Release Testing Job
  # --------------------------------------------------------------------------

  tests:
    environment: gcloud
    runs-on: ubuntu-latest
    steps:

    # --------------------------------------------------------------------------
    # Repository Checkout
    # --------------------------------------------------------------------------

    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: '^1.18'

    - name: cache go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-build-codegen-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-build-codegen-

    - name: checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    # --------------------------------------------------------------------------
    # Run Tests
    # --------------------------------------------------------------------------

    - name: run unit tests
      run: make test.unit

    - name: run integration tests
      run: make test.integration
      env:
        KONG_LICENSE_DATA: ${{ secrets.KONG_LICENSE_DATA }}

    - name: run e2e tests
      run: make test.e2e
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        GOOGLE_LOCATION: ${{ secrets.GOOGLE_LOCATION }}
        KONG_LICENSE_DATA: ${{ secrets.KONG_LICENSE_DATA }}

    # --------------------------------------------------------------------------
    # Release Tagging
    # --------------------------------------------------------------------------

    - name: tag the release
      run: |
        git tag ${{ github.event.inputs.tag }}
        git push origin refs/tags/${{ github.event.inputs.tag }}
