name: release-testing

on:
  push:
    tags:
      # NOTE: for help on how this tagging works see the RELEASE.md documentation.
      #       also see the `release.yaml` workflow which this workflow triggers upon success.
      - "do-release-*"

jobs:

  # --------------------------------------------------------------------------
  # Release Testing Job
  # --------------------------------------------------------------------------

  tests:
    environment: gcloud
    runs-on: ubuntu-latest
    steps:

    # --------------------------------------------------------------------------
    # Repository Checkout
    # --------------------------------------------------------------------------

    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17'

    - name: cache go modules
      uses: actions/cache@v2.1.6
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-build-codegen-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go

    - name: checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    # --------------------------------------------------------------------------
    # Verification
    # --------------------------------------------------------------------------

    - name: release tag verification
      run: go run internal/ci/release/tagging/main.go verify
      env:
        GIT_REF: ${{ github.ref }}

    # --------------------------------------------------------------------------
    # Run Tests
    # --------------------------------------------------------------------------

    - name: run unit tests
      run: make test.unit

    - name: run integration tests
      run: make test.integration
      env:
        KONG_ENTERPRISE_LICENSE: ${{ secrets.KONG_ENTERPRISE_LICENSE }}

    - name: run e2e tests
      run: make test.e2e
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        GOOGLE_LOCATION: ${{ secrets.GOOGLE_LOCATION }}
        KONG_ENTERPRISE_LICENSE: ${{ secrets.KONG_ENTERPRISE_LICENSE }}

    # --------------------------------------------------------------------------
    # Release Tagging
    # --------------------------------------------------------------------------

    - name: tag and push the release
      run: go run internal/ci/release/tagging/main.go retag
      env:
        GIT_REF: ${{ github.ref }}

    # --------------------------------------------------------------------------
    # Cleanup
    # --------------------------------------------------------------------------

    - name: cleanup release trigger tags
      run: go run internal/ci/release/tagging/main.go cleanup
      env:
        GIT_REF: ${{ github.ref }}

