name: release-testing

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'a git tag that needs to be created'
        required: true

jobs:

  # --------------------------------------------------------------------------
  # Release Testing Job
  # --------------------------------------------------------------------------

  tests:
    environment: gcloud
    runs-on: ubuntu-latest
    steps:

    # --------------------------------------------------------------------------
    # Repository Checkout
    # --------------------------------------------------------------------------

    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17'

    - name: cache go modules
      uses: actions/cache@v2.1.6
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-build-codegen-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go

    - name: checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

          #    # --------------------------------------------------------------------------
          #    # Run Tests
          #    # --------------------------------------------------------------------------
          #
          #    - name: run unit tests
          #      run: make test.unit
          #
          #    - name: run integration tests
          #      run: make test.integration
          #      env:
          #        KONG_ENTERPRISE_LICENSE: ${{ secrets.KONG_ENTERPRISE_LICENSE }}
          #
          #    - name: run e2e tests
          #      run: make test.e2e
          #      env:
          #        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          #        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          #        GOOGLE_LOCATION: ${{ secrets.GOOGLE_LOCATION }}
          #        KONG_ENTERPRISE_LICENSE: ${{ secrets.KONG_ENTERPRISE_LICENSE }}

    # --------------------------------------------------------------------------
    # Release
    # --------------------------------------------------------------------------

    - name: tagging the release
      run: |
        git tag ${{ github.event.inputs.tag }}
        git push --tags

    - name: triggering the release
      run: go run internal/ci/workflows/main.go release.yaml ${{ github.event.inputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ORG: "shaneutt"
        GITHUB_REPO: "kubernetes-testing-framework"
