name: Integration Tests

on: [pull_request]

jobs:
  kind-cluster-test:
    runs-on: ubuntu-latest
    steps:
    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16'
    - name: cache go modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-build-codegen-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go
    - name: checkout repository
      uses: actions/checkout@v2
    - name: run integration tests
      run: make test.integration
