name: Unit Tests

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16'
    - name: cache go modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-build-codegen-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go
    - name: checkout repository
      uses: actions/checkout@v2
    - name: run unit tests
      run: make test.unit
